name: workflow name
on:
  push:
    branches:
      - 'master'
      
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps: ...
    
-name: Checkout
uses: actions/checkout@v1

    name: Use Node 12.x
  
  uses: actions/setup-node@v1
  with:
    node-version: '12.x'
    
    "build:ci": "ng build --prod --sourceMap=false --base-href /YOUR_REPOSITORY_NAME_HERE/"
"test:ci": "ng test --watch=false --code-coverage --source-map true"

 name: Install dependencies
  run: npm ci
- name: Build
  run: npm run build:ci
- name: Test
  run: npm run test:ci
  - name: Archive build
  if: success()
  uses: actions/upload-artifact@v1
  with:
    name: deploy_dist
    path: dist
- name: Archive code coverage result
  if: success()
  uses: actions/upload-artifact@v1
  with:
    name: deploy_coverage
    path: coverage
